# VDBFUSION
voxel_size: 0.1
sdf_trunc: 0.3
space_carving: False
out_dir: "results"
apply_pose: True
preprocess: True

# Reconstruction
fill_holes: True
min_weight: 5.0

# Kitti
min_range: 2.0
max_range: 70.0
