# VDBFUSION
voxel_size: 0.1
sdf_trunc: 0.3
space_carving: False
out_dir: "results/"

# Reconstruction
fill_holes: False
min_weight: 5.0

# Kitti
apply_pose: True
min_range: 2.5
max_range: 120.0
correct_scan: True
